"""empty message

Revision ID: 181853a0b76c
Revises: a5040e5f2c62
Create Date: 2022-08-18 05:49:00.566316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181853a0b76c'
down_revision = 'a5040e5f2c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('looking_for_venue', sa.Boolean(), nullable=True))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'looking_for_venue')
    # ### end Alembic commands ###
